name: Run
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install bcrypt
      - run: echo pass | python simplebcrypt.py
      - run: echo Done
